default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password:

development:
  <<: *default
  database: restaurant_critic_development

test:
  <<: *default
  database: restaurant_critic_test

production:
  <<: *default
  database: restaurant_critic
